### ISSUE TITLE
问题很多不是关键，关键是工程太胖啊，操作都好繁琐

### ISSUE THREAD

**Issue by lzpong** [JustWayward/BookReader#171]
读个cache 都经常有报错。。。。。
导致书籍空了，也不好调试。。。。
```
com.justwayward.reader W/System.err:     at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1330)
com.justwayward.reader W/System.err:     at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1242)
com.justwayward.reader W/System.err:     at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1835)
com.justwayward.reader W/System.err:     at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:761)
com.justwayward.reader W/System.err:     at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1983)
com.justwayward.reader W/System.err:     at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1940)
com.justwayward.reader W/System.err:     at com.justwayward.reader.utils.ACache.getAsObject(ACache.java:480)
com.justwayward.reader W/System.err:     at com.justwayward.reader.manager.CollectionsManager.getCollectionList(CollectionsManager.java:68)
com.justwayward.reader W/System.err:     at com.justwayward.reader.manager.CollectionsManager.getCollectionListBySort(CollectionsManager.java:82)
com.justwayward.reader W/System.err:     at com.justwayward.reader.ui.fragment.RecommendFragment.onRefresh(RecommendFragment.java:367)
com.justwayward.reader W/System.err:     at com.justwayward.reader.ui.fragment.RecommendFragment.configViews(RecommendFragment.java:120)
com.justwayward.reader W/System.err:     at com.justwayward.reader.base.BaseFragment.onViewCreated(BaseFragment.java:67)
```

**Comment by smuyyh** [comment]
那就自己写~~  以前也就是随便写出来玩玩的
