### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by LeeeYudE** [JustWayward/BookReader#18]
发现在看书页面点击返回键会报错
com.justwayward.reader E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                              at com.justwayward.reader.manager.CollectionsManager.isCollected(CollectionsManager.java:79)
                                                                              at com.justwayward.reader.ui.activity.ReadActivity.onKeyDown(ReadActivity.java:529)
                                                                              at android.view.KeyEvent.dispatch(KeyEvent.java:2693)
                                                                              at android.app.Activity.dispatchKeyEvent(Activity.java:2785)
                                                                              at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
                                                                              at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
                                                                              at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:241)
                                                                              at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2389)
                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4557)
                                                                              at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4513)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4035)
                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4088)
                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4054)
                                                                              at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4191)
                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4062)
                                                                              at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4248)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4035)
                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4088)
                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4054)
                                                                              at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4062)
                                                                              at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4035)
                                                                              at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4088)
                                                                              at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4054)
                                                                              at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4224)
                                                                              at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4394)
                                                                              at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2285)
                                                                              at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1909)
                                                                              at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1900)
                                                                              at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2262)
                                                                              at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                              at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                              at android.os.MessageQueue.next(MessageQueue.java:148)
                                                                              at android.os.Looper.loop(Looper.java:151)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5667)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
09-30 16:13:38.617 32756-32756/com.justwayward.reader E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.justwayward.reader, PID: 32756
                                                                        java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
                                                                            at com.justwayward.reader.manager.CollectionsManager.isCollected(CollectionsManager.java:79)
                                                                            at com.justwayward.reader.ui.activity.ReadActivity.onKeyDown(ReadActivity.java:529)
                                                                            at android.view.KeyEvent.dispatch(KeyEvent.java:2693)
                                                                            at android.app.Activity.dispatchKeyEvent(Activity.java:2785)
                                                                            at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
                                                                            at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:50)
                                                                            at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:241)
                                                                            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2389)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4557)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4513)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4035)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4088)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4054)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4191)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4062)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4248)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4035)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4088)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4054)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4062)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4035)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4088)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4054)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4224)
                                                                            at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4394)
                                                                            at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2285)
                                                                            at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1909)
                                                                            at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1900)
                                                                            at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2262)
                                                                            at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                            at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                            at android.os.MessageQueue.next(MessageQueue.java:148)
                                                                            at android.os.Looper.loop(Looper.java:151)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5667)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by smuyyh** [comment]
你这是比较早的代码了吧？更新一下~
