### ISSUE TITLE
进入小说页面出现直接报错

### ISSUE THREAD

**Issue by billsinla** [JustWayward/BookReader#33]
java.lang.UnsatisfiedLinkError: Couldn't load hci_curl from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.justwayward.reader-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.justwayward.reader-1, /system/lib]]]: findLibrary returned null
                      at java.lang.Runtime.loadLibrary(Runtime.java:358)
                      at java.lang.System.loadLibrary(System.java:526)
                      at com.sinovoice.hcicloudsdk.api.tts.HciCloudTts.<clinit>(SourceFile:79)
                      at com.sinovoice.hcicloudsdk.player.TTSCommonPlayer.init(SourceFile:279)
                      at com.justwayward.reader.utils.TTSPlayerUtils.getTTSPlayer(TTSPlayerUtils.java:18)
                      at com.justwayward.reader.ui.activity.ReadActivity.initDatas(ReadActivity.java:234)
                      at com.justwayward.reader.base.BaseActivity.onCreate(BaseActivity.java:53)

**Comment by smuyyh** [comment]
你这个是什么时候的代码？这个是语音合成的so库找不到。卸载重新装一下试试，so库在libs下有

**Comment by billsinla** [comment]
AndroidStudio模拟器不能运行，应该是so包不一样，在小米手机上面可以

**Comment by smuyyh** [comment]
哦那可能是cpu差异。手机应该是没问题的~

**Comment by billsinla** [comment]
嗯，大神给你赞一个，模拟器应该是x86的包，估计得去重新找找

**Comment by smuyyh** [comment]
hicloud官网 貌似只提供那一套，不行的话  那估计就不支持了~
