### ISSUE TITLE
android studio2.2安装打开本地txt文件，报下面的错误信息，乐视手机Le X620

### ISSUE THREAD

**Issue by mppy1** [JustWayward/BookReader#35]
10-14 15:21:39.496 9473-9473/com.justwayward.reader E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.justwayward.reader, PID: 9473
                                                                      java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                                                                          at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:4878)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:4951)
                                                                          at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:7352)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3101)
                                                                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2917)
                                                                          at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1482)
                                                                          at android.support.v7.widget.RecyclerView.access$400(RecyclerView.java:147)
                                                                          at android.support.v7.widget.RecyclerView$1.run(RecyclerView.java:294)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:696)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:628)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
                                                                          at android.os.Handler.handleCallback(Handler.java:815)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                          at android.os.Looper.loop(Looper.java:207)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5905)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

**Comment by smuyyh** [comment]
打开本地txt？是在文件管理器打开的？还是扫描本地书籍那

**Comment by smuyyh** [comment]
@mppy1 请问这个问题是必现么？

**Comment by mppy1** [comment]
是在扫描本地书籍那里，这个问题是发现 的

**Comment by mppy1** [comment]
@smuyyh 还有翻页txt文件，首页和最后一页，toast提醒后翻起的角就回不去了。

**Comment by smuyyh** [comment]
好的。我看看

**Comment by smuyyh** [comment]
两个问题，解决了~。上面那个报错 有空帮忙再试试哈~ 应该是不会了

**Comment by mppy1** [comment]
确认已经OK了
