### ISSUE TITLE
大神麻烦看看BookApi的getBookToc方法，好像是这个函数导致追书不及时啊

### ISSUE THREAD

**Issue by anshe80** [JustWayward/BookReader#48]
大神，看你的代码有一段时间了，发现追书体验还不是很好啊。
       最近大神在MainActivityPresenter类里添加同步书架的功能，发现有些书可用，有些书（超品相师）更新直接还退回去了（我打印的语句：MainActivityPresenter.java:92] - 网络最新lastChapter=第2582章 玉柔 本地最新章节book.lastChapter=第2751章 选择），操作方式：先在书籍详细界面点击追书后，返回书架界面，点击同步书架。ps：难不成是VIP章节导致的？不过在不保存到本地（保存到本地没试过），在书籍详细界面点击不追书，再点追书更新，主界面显示的最新章节就对了，不过进去阅读界面的目录还是没有更新。
     此外，大神可以把lastChapter字段的数字提取出来，根据数字大小判断是否有更新，推送就不必了（目前实现的方式感觉就是写个服务隔断时间就去刷新，这样太恶心了）。

**Comment by smuyyh** [comment]
追书获取目录有好多个接口，那时候看了很久 还是不知道他怎么区分的。所以找了个大部分能用的接口，你有尝试过么？有没有发现这个请求目录接口的规律？

**Comment by anshe80** [comment]
我只是追随着大神的脚步在看代码，没有去抓包查看追书的接口。
我记得追书以前有个换源的功能，就是切换书籍的数据来源，不同的数据来源在更新方面会有不同，也许就是这个原因才会存在获取目录有好多接口，这样估计大神就要写一个智能获取目录的接口了，或者简单点就像追书直接给个换源功能，让用户去换个最新的数据来源。

**Comment by smuyyh** [comment]
换源砍掉了 没有做这个。后面再研究研究获取目录的接口

**Comment by anshe80** [comment]
小说一般都在晚上更新，估计你要等晚上才可以。

**Comment by anshe80** [comment]
bookAPIService的getBookRead方法好像挺好使的，刚试了一下，更新还算及时。

**Comment by anshe80** [comment]
在线阅读时，缓存方式好像有问题，在跳到下一章时，会因为下一章下载失败，阅读时直接跳过这些下载失败的章节。

**Comment by smuyyh** [comment]
@anshe80 后面再来看看  最近赶公司的项目  比较没时间了~~  你可以先帮忙看看要怎么改啊哈哈

**Comment by smuyyh** [comment]
@anshe80 解决了。有空可以试试哈~

**Comment by anshe80** [comment]
@smuyyh 现在出现了另外一个问题：在看完已更新的章节后，再次有更新章节，进去看的时候会出现点击下一页崩溃，重启后还是无法查看这本书的任意章节。感觉应该让主页的章节和阅读时的章节同步或者共享变量，没必要刷新后进入看书还再次去获取网络章节。
大神什么时候把菜单的同步书架放到下拉刷新里面。

**Comment by smuyyh** [comment]
错误信息是什么呢？更新章节好像不太好测吧

**Comment by anshe80** [comment]
崩溃的log没能及时拔掉手机，被覆盖了，只剩下这一部分而已，下次有空再试试。
有更新后，点击阅读，看到进度是100%，此时立马点击下一页，就会崩溃，不过好像要是等一会的话就不会。
11-18 22:30:30.802 23225-23225/com.justwayward.reader E/Zygote: MountEmulatedStorage()
11-18 22:30:30.802 23225-23225/com.justwayward.reader E/Zygote: v2
11-18 22:30:30.812 23225-23225/com.justwayward.reader E/SELinux: [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
崩溃重启后再次立马点击这本书（但是过一段时间再点击就可以正常查看了），就无法查看内容了，log看到保存的历史阅读位置是对的，但是阅读界面却没有内容，而且点击目录此时显示是在第一章的位置，但是log显示的却是上次阅读的位置。下面是无法查看时的log：
11-18 22:31:14.592 23225-23225/com.justwayward.reader E/art: No implementation found for void com.sinovoice.hcicloudsdk.common.utils.CloudLog.hciLog(int, java.lang.String, java.lang.String, java.lang.String) (tried Java_com_sinovoice_hcicloudsdk_common_utils_CloudLog_hciLog and Java_com_sinovoice_hcicloudsdk_common_utils_CloudLog_hciLog__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for void com.sinovoice.hcicloudsdk.common.utils.CloudLog.hciLog(int, java.lang.String, java.lang.String, java.lang.String) (tried Java_com_sinovoice_hcicloudsdk_common_utils_CloudLog_hciLog and Java_com_sinovoice_hcicloudsdk_common_utils_CloudLog_hciLog__ILjava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at com.sinovoice.hcicloudsdk.common.utils.CloudLog.hciLog(Native Method)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at com.sinovoice.hcicloudsdk.common.utils.CloudLog.hLog(SourceFile:83)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at com.sinovoice.hcicloudsdk.common.utils.CloudLog.w(SourceFile:37)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at com.sinovoice.hcicloudsdk.common.utils.PlatformUtil.loadLibraryIfExist(SourceFile:48)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at com.sinovoice.hcicloudsdk.api.tts.HciCloudTts.<clinit>(SourceFile:89)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at com.sinovoice.hcicloudsdk.player.TTSCommonPlayer.init(SourceFile:279)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at com.justwayward.reader.utils.TTSPlayerUtils.getTTSPlayer(TTSPlayerUtils.java:33)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at com.justwayward.reader.ui.activity.ReadActivity.initDatas(ReadActivity.java:276)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at com.justwayward.reader.base.BaseActivity.onCreate(BaseActivity.java:67)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at android.app.Activity.performCreate(Activity.java:6288)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at android.app.ActivityThread.access$900(ActivityThread.java:177)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at android.os.Looper.loop(Looper.java:145)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5942)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
11-18 22:31:14.592 23225-23225/com.justwayward.reader W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by anshe80** [comment]
大神！你的更新逻辑是不是这样？：1、先在书架更新最新章节的提示，不处理已经下载的章节，仅考虑章节数是不是增加了；2、用户知道书有更新进入阅读界面，在阅读界面重新从服务器获取所有的章节，不处理已经下载的章节和最新章节的融合，直接替换所有的章节信息。可能就是因为这样，导致了更新后，章节内容和标题不匹配的情况，这很有可能是章节的那个隐数字和章节标题数字不总是相同的一一对应导致的，因为隐数字和章节标题数字不一样，而本地保存的章节文件名是以隐数字命名的吧，而读取的时候默认先读取本地的。

**Comment by smuyyh** [comment]
缓存的是目录，目录次序对应章节文件序号。所以假如他中间多出一章来…那只能清除缓存，重新获取目录及章节文件才行！

书架有更新章节目前也没有提示，只能手动点击同步书架。这个也没法应对中间多出一章的情况。

目前这种只能清除章节缓存才行了。 你有没有什么好的办法？

**Comment by anshe80** [comment]
你现在有手动同步书架的功能了，书架自动更新章节的提示，其实挺好实现的了，你没有写过服务线程吗？启动书架后，利用后台服务连接服务器验证最新章节，就可以了，这只是将手动触发更新变为定条件触发更新而已。
至于缓存的目录，现在想到两个不是很完美的方法：1、假如在第一次保存书籍的目录时，此时的目录是完全正确的，那么每次更新都只是把最新的章节添加到原来保存的目录中，而不是目录全部替换成服务器的目录，这种方法要基于假如的条件成立，才不会出现问题。2、牺牲点性能，老老实实将旧的目录和从服务器获取到的目录进行对比合并出新的目录，这时候就需要看算法设计得怎么样了。

**Comment by smuyyh** [comment]
主要不是说服务的问题。目前没有判断更新的接口，只能说重新获取一遍目录进行比对，这种方式麻烦。中间多出一章或少了一章，或者章节title变了，与本地的章节缓存就冲突了，这些都比较难判断。

**Comment by anshe80** [comment]
你想找到追书神器的更新接口？

**Comment by smuyyh** [comment]
如果有当然再好不过了😄但是他应该是在服务端同步的吧，和帐号绑定了吧？然后有更新就推送信息？这方面没有去研究过

**Comment by anshe80** [comment]
确实应该是和帐号绑定的，不过你可以先对list过滤一下重复章节的链接，还是可以的。至于更新和缓存的问题，暂时没想到好的方法。

**Comment by anshe80** [comment]
今天试着过滤一下重复的章节，本想对ReadActivity的showBookToc方法里的目录去重，本想通过链接是否相同去重，结果发现即使链接不同，内容还是可能一样，或许这是追书神器的API问题。

**Comment by smuyyh** [comment]
难搞~  你可以考虑自己做一套服务端  哈哈  这样就随心所欲了

**Comment by wby238** [comment]
记得看过别人的文章说是atoc还是btoc（具体哪个忘了……）是获取可换源的源地址的……
最近写了一个抓包后下载章节内容的小程序，找了找发现还是book.my716,com这个源提供的内容最好，跟正版源几乎一模一样，或许用这个设置为默认源最好？

**Comment by anshe80** [comment]
中间多出一章或少了一章的问题，想到的处理方式：将保存的章节文件名仅数字变为数字+章节标题，数字改变会浪费磁盘空间，产生无用的垃圾。但是在实验过程中，发现有些ChapterRead.Chapter的章节标题和目录竟然不一样；目前，考虑在FileUtils.getChapterPath方法中，章节标题通过空格分割去掉第一个，后面所有的词组成需要保存的章节标题。

**Comment by anshe80** [comment]
醉了！测试的书籍，点击“同步书架”后，章节标题和目录的又一样了。
