### ISSUE TITLE
无法打开txt

### ISSUE THREAD

**Issue by hengtongjie** [JustWayward/BookReader#58]
扫描本地文件，扫面不到txt文件，在本地文件夹里点击txt,选择用本软件打开，程序崩溃，这个请完善吧，另外还有一个小要求，可否加入书签功能。

**Comment by smuyyh** [comment]
什么时候的代码？崩溃信息贴上~

**Comment by hengtongjie** [comment]
ok 崩溃信息如下  我下载的最新的代码
/com.justwayward.reader E/BookReader: [main(1): CrashHandler.java:182] - ---------------------sta--------------------------SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@1d6fb81
                                                                  versionCode=1
                                                                  BOARD=APQ8084
                                                                  IS_TRANSLATION_ASSISTANT_ENABLED=false
                                                                  BOOTLOADER=N9108VZMU1DPI1
                                                                  TYPE=user
                                                                  ID=MMB29M
                                                                  TIME=1473659659000
                                                                  BRAND=samsung
                                                                  TAG=Build
                                                                  SERIAL=293845c6
                                                                  HARDWARE=qcom
                                                                  SUPPORTED_ABIS=[Ljava.lang.String;@ff09426
                                                                  CPU_ABI=armeabi-v7a
                                                                  RADIO=unknown
                                                                  IS_DEBUGGABLE=false
                                                                  MANUFACTURER=samsung
                                                                  SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@d614b68
                                                                  isOSUpgradeKK2LL=true
                                                                  TAGS=release-keys
                                                                  IS_SYSTEM_SECURE=false
                                                                  CPU_ABI2=armeabi
                                                                  UNKNOWN=unknown
                                                                  USER=dpi
                                                                  FINGERPRINT=samsung/trltezm/trltechn:6.0.1/MMB29M/N9108VZMU1DPI1:user/release-keys
                                                                  FOTA_INFO=1473660023
                                                                  HOST=SWDD5823
                                                                  PRODUCT=trltezm
                                                                  versionName=1.0
                                                                  DISPLAY=MMB29M.N9108VZMU1DPI1
                                                                  MODEL=SM-N9108V
                                                                  DEVICE=trltechn
                                                                  IS_SECURE=false
                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.justwayward.reader/com.justwayward.reader.ui.activity.ReadActivity}: java.lang.StringIndexOutOfBoundsException: length=37; regionStart=32; regionLength=-33
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                      at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:158)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                   Caused by: java.lang.StringIndexOutOfBoundsException: length=37; regionStart=32; regionLength=-33
                                                                      at java.lang.String.startEndAndLength(String.java:298)
                                                                      at java.lang.String.substring(String.java:1087)
                                                                      at com.justwayward.reader.ui.activity.ReadActivity.initDatas(ReadActivity.java:222)
                                                                      at com.justwayward.reader.base.BaseActivity.onCreate(BaseActivity.java:52)
                                                                      at android.app.Activity.performCreate(Activity.java:6876)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                      at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:158) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7225) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                  java.lang.StringIndexOutOfBoundsException: length=37; regionStart=32; regionLength=-33
                                                                      at java.lang.String.startEndAndLength(String.java:298)
                                                                      at java.lang.String.substring(String.java:1087)
                                                                      at com.justwayward.reader.ui.activity.ReadActivity.initDatas(ReadActivity.java:222)
                                                                      at com.justwayward.reader.base.BaseActivity.onCreate(BaseActivity.java:52)
                                                                      at android.app.Activity.performCreate(Activity.java:6876)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                      at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:158)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by smuyyh** [comment]
好的。晚点有空处理一下~

**Comment by hengtongjie** [comment]
好的 可否加一个书签的功能

**Comment by hengtongjie** [comment]
你好，请问上面反馈的问题解决了吗？以及调起菜单时长时间不操作 会翻页卡在中间位置。

**Comment by smuyyh** [comment]
这个看起来好像是文件路径的问题。我稍微调整了一下代码  你可以再试试

另外，扫描不到本地书籍？一个文件也没有？扫描调的是系统的provider，类似图库，扫描不到的文件可能是没有加入。

**Comment by mppy1** [comment]
会不会没权限，6.0以上安装的tagetVersion是23及以上？

**Comment by smuyyh** [comment]
@mppy1 目前用的targetSdkVersion是22，就没再申请权限。

**Comment by smuyyh** [comment]
@hengtongjie 书签功能已增加！
